# Training Large Models at One-Tenth the Cost, With Better Results: How Is That Possible?

In 2025, the reinforcement learning compute bill for training a model comparable to GPT-4 was roughly several million dollars. Over the past six months, leading models such as Qwen3, Gemma 2, and MiMo have all shifted toward a new method: the same quality, with compute costs cut by 90%.

This is not clickbait. Thinking Machines Lab reported measured results on the AIME 2024 math competition: the new method reached 74.4% accuracy with 1,800 GPU hours, while traditional reinforcement learning used 17,920 GPU hours and reached only 67.6%.

**Costs fell by tenfold, and performance improved.** In machine learning, this is close to a "free lunch."

The method is called On-Policy Distillation, abbreviated below as OPD. It comes from a Google DeepMind paper published at ICLR in early 2024: "On-Policy Distillation of Language Models: Learning from Self-Generated Mistakes."

Below, we break down three questions: what OPD actually does, why it works so well, and which companies are already using it.

---

## The Post-Training Dilemma for Large Language Models

To understand OPD, we first need to understand the problem it is trying to solve.

Large language model training has two stages: pretraining and post-training. Pretraining teaches the basic patterns of language from massive text corpora; post-training makes the model smarter and more aligned with user intent. The topic here is post-training.

Today, post-training mainly uses two methods, each with a serious weakness.

**Method 1: Supervised Fine-Tuning (SFT)**

Prepare a batch of high-quality "question-answer" pairs and let the model learn by imitation. For example, show the model standard solutions to 100 math problems and ask it to copy the reasoning style.

The problem is that the model learns from the teacher's text, but at inference time it generates its own text. These two distributions are different. It is like reading 100 perfect-scoring essays, then writing in your own style: the mistakes you are likely to make may never appear in those perfect essays. The technical term is "train-test distribution mismatch," and it is the fundamental bottleneck of supervised fine-tuning.

**Method 2: Reinforcement Learning (RL)**

The model generates answers on its own, and then receives only final feedback on whether the result is correct.

The advantage is clear: the model learns from the text it generated itself, so there is no distribution mismatch. The disadvantage is equally clear. If a math solution has 50 steps and the only feedback is "wrong," the model has to guess which step caused the problem. This is called a "sparse reward." Learning from so little information requires enormous sampling and highly complex optimization algorithms, making training expensive and unstable.

![GKD outperforms traditional methods across all three tasks](../../assets/opd/fig1-gkd-performance.png)

Putting the two methods in a table makes the empty quadrant obvious:

| Method | Sampling method | Reward signal |
|------|--------|--------|
| Supervised Fine-Tuning (SFT) | Off-policy (text comes from teacher/expert) | Dense (token-by-token supervision) |
| Reinforcement Learning (RL) | On-policy (text generated by the student itself) | Sparse (only final outcome feedback) |
| **OPD (the focus here)** | **On-policy (text generated by the student itself)** | **Dense (teacher gives token-by-token feedback)** |

OPD's approach is simple: let the model learn from its own text, while also giving it precise feedback at every step. Does that sound like having both pieces of cake at once? Exactly. That is why it is called a "free lunch."

---

## Core Idea: The Student Solves the Problem, and the Teacher Marks It Step by Step

Return to a more intuitive analogy.

Suppose you are a new hire, and your company assigns you a senior mentor. Traditional training (SFT) means the mentor writes a model answer and you copy it once. Reinforcement learning means you solve the problem yourself, and at the end someone only tells you "pass" or "fail."

OPD does something very different: **you solve the problem in your own way, and then the mentor annotates your work line by line**: "this step is right," "this is where you started drifting," "this choice directly caused the later error."

The key difference is that the teacher comments on what the student actually wrote, not on a model answer the student would never produce.

In concrete training terms, the workflow has four steps:

**Step 1: The student generates text.** Give the student model a question and let it write a full answer using its current ability. These answers carry the student's own "accent" and "bad habits," which is exactly what we want.

**Step 2: The teacher scores each token.** Feed the student's answer into the teacher model, and let the teacher output its probability distribution for every token the student wrote. This computation is cheap: it only requires one forward pass and no sampling. This is one key reason OPD is cheaper than reinforcement learning. RL requires repeated sampling and evaluation; the teacher only needs to "read through" the student's answer once.

**Step 3: Compute the token-level gap.** At each token position, compare the teacher's probability distribution with the student's. This gap is a dense reward signal. It can tell the student precisely: at token 37, you made a poor choice, and the teacher would have gone in a very different direction.

**Step 4: Update the student model.** Use these token-level signals to update the student's parameters, so it makes better choices in similar positions next time.

---

## How Should the Teacher "Score" the Student?

This section goes a bit deeper into the technical details. If you want to skip the formulas, read the "plain-English translation" after each one and you will still understand the rest.

OPD uses KL divergence to measure the "gap between teacher and student." But KL divergence has two directions, and the choice matters enormously.

**Forward KL divergence** (used in traditional distillation):

$$D_{KL}(P_{teacher} \| P_{student}) = \sum_x P_{teacher}(x) \cdot \log \frac{P_{teacher}(x)}{P_{student}(x)}$$

Plain-English translation: you must study every topic the teacher might test. Every word the teacher considers possible must be covered by the student.

Effect: the student's output becomes more diffuse and conservative, touching a bit of everything but mastering nothing. The technical term is "mode covering."

**Reverse KL divergence** (used by OPD):

$$D_{KL}(P_{student} \| P_{teacher}) = \sum_x P_{student}(x) \cdot \log \frac{P_{student}(x)}{P_{teacher}(x)}$$

Plain-English translation: every topic you choose to study must be correct, but you do not need to cover every possible topic. Every direction selected by the student must also be accepted by the teacher.

Effect: the student concentrates on learning one strong strategy well, instead of spreading itself thin across all possibilities. The technical term is "mode seeking."

![Quality-diversity tradeoff between forward KL and reverse KL](../../assets/opd/fig2-kl-tradeoff.png)

Why is reverse KL better suited to large-model distillation? Because we do not need a small model to learn every capability of a large model; that is impossible. What we need is for the small model to do the things it can do as well as possible. Reverse KL encourages precisely that kind of "specialization" rather than "coverage."

There is also an elegant coincidence, which is really a mathematical necessity: reverse KL has to be computed on the student's own samples. Mathematically, it naturally requires that "the student solves the problem itself." Forward KL can be computed on teacher samples, so traditional distillation never needed the student to generate its own text.

The core design of "the student learns from its own work" is not only intuitive; it is also built into the loss function. Form and objective are perfectly aligned.

**From an information perspective:** In reinforcement learning, the model generates an answer with hundreds of tokens and receives only one final score. Each iteration provides only O(1) bits of information. In OPD, the teacher gives a full probability distribution at every token. If an answer has N tokens, each iteration provides O(N) bits of information. It is like grading an exam: reinforcement learning writes only a final score at the bottom of the paper, while OPD writes comments beside every question. The information content differs by two to three orders of magnitude.

That is the root reason OPD is so data-efficient.

---

## GKD: One Knob From Traditional Distillation to OPD

The concrete algorithm proposed in the paper is called GKD (Generalized Knowledge Distillation), a unified framework. Its core is a parameter, lambda:

- **lambda = 0**: learn entirely from the teacher's text, reducing to traditional distillation
- **lambda = 1**: learn entirely from the student's own text, becoming pure OPD
- **0 < lambda < 1**: mix the two data sources

![GKD algorithm pseudocode](../../assets/opd/fig3-algorithm1.png)

The engineering implementation is very intuitive: during training, use the current student model to generate an answer, ask the teacher model to score that answer token by token, compute the gap, and update the student parameters. The whole process is almost as simple as ordinary fine-tuning. The only extra cost is one additional "student sampling" step.

The paper finds that the closer lambda is to 1, the better the results. In other words, having the student learn from its own text works far better than having it learn from the teacher's text.

---

## Experimental Results: Let the Data Speak

The paper ran experiments on three very different tasks. Compared with traditional distillation, GKD delivered improvements of 1.7x to 2.1x. This was not a few percent better; it was more than twice as good in some settings.

| Task | Dataset | Improvement vs. traditional distillation |
|------|--------|----------------|
| Summarization | XSum | 2.1x |
| Machine translation | WMT | 1.7x |
| Math reasoning | GSM8K | 1.9x |

![GSM8K math reasoning comparison, where OPD outperforms all methods](../../assets/opd/fig4-gsm8k.png)

But the most striking finding concerns data efficiency:

![Data efficiency comparison: GKD with 5% of the data beats traditional distillation with 100% of the data](../../assets/opd/fig5-data-efficiency.png)

> **GKD using only 5% of the data outperformed traditional distillation using 100% of the data.**

If you have 100,000 training examples, running all of them with the traditional method performs worse than running only 5,000 examples with GKD.

The paper also includes a blockbuster result: a tiny model with only 77 million parameters, distilled through GKD, beat the 540 billion-parameter PaLM on multiple tasks. That is a 7,000x size gap, with the smaller model performing better.

![MMLU/BBH general capability comparison](../../assets/opd/fig6-mmlu-bbh.png)

It is not that small models cannot learn. The previous teaching method simply was not good enough.

---

## Industrial Adoption: From Paper to Production

Start with a set of real-world results:

| Method | GPU hours | AIME'24 accuracy |
|------|---------|---------------|
| Traditional reinforcement learning | 17,920 | 67.6% |
| OPD | 1,800 | 74.4% |

These are Thinking Machines Lab's measured results on the American Invitational Mathematics Examination (October 2025). Cost fell by nearly tenfold, while accuracy rose by almost 7 percentage points.

Companies moved quickly:

**Google Gemma 2 (August 2024):** The paper authors' own organization used the method directly in Google's open-source model.

**Qwen3 (May 2025):** Alibaba's Tongyi Qianwen technical report was the first to systematically describe industrial-scale OPD practice. It clearly stated that OPD required only one-tenth of the GPU time of the full reinforcement learning pipeline while achieving comparable or better results.

**MiMo-V2-Flash (January 2026):** Validated OPD in multimodal settings, showing the method is not limited to pure text.

**GLM-5:** Zhipu also adopted similar on-policy distillation techniques in its next-generation model.

From a 2024 academic paper to a mainstream post-training paradigm in 2026, OPD has industrialized remarkably fast.

---

## OPD's Limits and Future

OPD has one structural prerequisite: **you must have a sufficiently strong teacher model.** In reinforcement learning, the reward signal can come from a rule-based verifier (for example, directly checking whether a math answer is correct), so it does not necessarily require a larger language model. In OPD, however, the teacher must be clearly stronger than the student on the target task.

This points to two especially important directions:

**Hybrid OPD + RL training.** Qwen3's practice already hints at this path: first use OPD to cheaply and stably improve baseline capability, then use RL for fine-grained tuning on specific dimensions. This may become the standard post-training workflow.

**Distilling reasoning models.** With the emergence of reasoning models such as o1/o3, efficiently distilling long-chain reasoning ability into smaller models is a highly promising use case for OPD. DeepSeek-R1 has already shown the enormous potential of distilling from large reasoning models into smaller ones.

In addition, self-distillation (letting the model serve as its own teacher) and multi-teacher fusion are also worth watching, though they remain in early exploration.

---

## Closing Thoughts

OPD's core insight is simple: students learn more effectively from their own mistakes than from copying someone else's correct answers. But "learning from your own mistakes" requires step-by-step guidance from a good teacher, not merely a final grade.

When we put that simple insight into a rigorous mathematical framework (reverse KL divergence + on-policy sampling), we get a method that cuts costs by an order of magnitude while improving results.

> In the second half of the large-model race, the winner may no longer be whoever spends the most money, but whoever trains more intelligently. OPD is the first shot in that shift, but it certainly will not be the last.

---

**Original paper:**
- arXiv: https://arxiv.org/abs/2306.13649

*Reference: Agarwal, R. et al. "On-Policy Distillation of Language Models: Learning from Self-Generated Mistakes." ICLR 2024.*
